# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    clear_derived_data
    xcversion(version: "10.1")
  end

  desc "Run all tests"
  lane :test do
    reset_simulator_contents
    scan(device: "iPhone X", scheme: "RoomFinderPro")
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    puts("this is my first 🚀 lane")
  end
end
